SELECT HISTORY_ID, 
    FLOOR( COALESCE(
    (SELECT (100 - MAX(DISCOUNT_RATE)) / 100
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAST(REPLACE(DURATION_TYPE, '일 이상', '') AS SIGNED) <= (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
    AND CAR_TYPE = '트럭'), 1) * DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC
